# Generated by Django 4.0.4 on 2022-05-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_author_books_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='title_of_book',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='title',
            new_name='title_of_genre',
        ),
    ]
